# Exercise 3

In [2]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
from ucimlrepo import fetch_ucirepo
breastcancer = fetch_ucirepo(id=15)
spambase = fetch_ucirepo(id=94)
X = breastcancer.data.features
y = breastcancer.data.targets

# 3.1

In [4]:
X.head()

,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses
0,5,1,1,1,2,1.0,3,1,1
1,5,4,4,5,7,10.0,3,2,1
2,3,1,1,1,2,2.0,3,1,1
3,6,8,8,1,3,4.0,3,7,1
4,4,1,1,3,2,1.0,3,1,1

In [5]:
X.drop(columns=['Single_epithelial_cell_size'], inplace=True)
X.head()

,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses
0,5,1,1,1,1.0,3,1,1
1,5,4,4,5,10.0,3,2,1
2,3,1,1,1,2.0,3,1,1
3,6,8,8,1,4.0,3,7,1
4,4,1,1,3,1.0,3,1,1

Single_epithelial_cell_size column is succesfully droped.

# 3.2

In [6]:
y.head()

   Class
0      2
1      2
2      2
3      2
4      2

In [7]:
y = y.replace({2: -1, 4: 1})
y.head()

   Class
0     -1
1     -1
2     -1
3     -1
4     -1

In [9]:
np.unique(y)

array([-1,  1])

The 2s and 4s are successfully replaced by -1s and 1s.